version: '3'

services:
  frontend:
    build: ./recipe-app
    ports:
      - '4200:80'
    networks:
      - my-network
  backend:
    build: ./restapi2022-S00165540
    ports:
      - '3000:3000'
    networks:
      - my-network
  database:
    image: mongo
    ports:
      - '27017:27017'
    networks:
      - my-network
    volumes:  
      - db-data:/data/db
  nginx:
    image: nginx
    ports:
      - '90:80'
    volumes:
      - 
    networks:
      - my-network

networks:
  my-network:
  
    driver: bridge